; Build configuration for macropad
; locks dependencies to known working versions


[env:lolin_s2_mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = lolin_s2_mini
framework = arduino
lib_deps = 
	aharshac/StringSplitter@^1.0.0
	bblanchon/ArduinoJson@^7.4.2
	rw0402/littlefs@^2.9.3
